[package]
name = "grpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum-tracing-opentelemetry = { path = "../..", features = ["otlp", "tracing_subscriber_ext"] }
prost = "0.11.2"
tokio = { version = "1.0", features = ["full"] }
tonic = { version = "0.8.2", features = ["transport", "channel", "codegen", "prost"], default-features = false }

[build-dependencies]
tonic-build = { version = "0.8.2", default-features = false, features = ["transport", "prost"] }

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
