[package]
name = "axum-tracing-opentelemetry"
description = "Middlewares and tools to integrate axum + tracing + opentelemetry"
version = "0.4.0"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["axum", "tracing", "opentelemetry"]
categories = ["web-programming"]
repository = "https://github.com/davidB/axum-tracing-opentelemetry"
homepage = "https://github.com/davidB/axum-tracing-opentelemetry"

[dependencies]
axum = "0.5"
# axum-core = "0.2"
http = "0.2"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", features = [
  "rt-tokio",
], optional = true }
opentelemetry-semantic-conventions = { version = "0.10", optional = true }
opentelemetry-otlp = { version = "0.11", optional = true, features = [
  "http-proto",
] }
tower-http = { version = "0.3", features = ["trace"] }
tracing = "0.1"
tracing-opentelemetry = "0.18"

[dev-dependencies]
assert-json-diff = "2.0.1"
opentelemetry-otlp = { version = "0.11", features = [
  "http-proto",
  "reqwest-client",
  "reqwest-rustls",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17", features = ["full"] }
tower = "0.4"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }


[features]
jaeger = ["opentelemetry-jaeger", "tracer"]
otlp = ["opentelemetry-otlp", "tracer"]
tracer = ["opentelemetry-semantic-conventions"]
