[package]
name = "axum-tracing-opentelemetry"
description = "Middlewares and tools to integrate axum + tracing + opentelemetry"
version = "0.10.0"
edition = "2021"
readme = "README.md"
license = "CC0-1.0"
keywords = ["axum", "tracing", "opentelemetry"]
categories = ["web-programming"]
repository = "https://github.com/davidB/axum-tracing-opentelemetry"
homepage = "https://github.com/davidB/axum-tracing-opentelemetry"

[dependencies]
axum = "0.6"
# axum-core = "0.3"
futures = "0.3"
http = "0.2"
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-aws = { version = "0.6", optional = true }
opentelemetry-jaeger = { version = "0.17", features = [
  "rt-tokio",
], optional = true }
opentelemetry-otlp = { version = "0.11", optional = true, features = [
  "http-proto",
] }
opentelemetry-semantic-conventions = { version = "0.10", optional = true }
opentelemetry-zipkin = { version = "0.16", features = [], optional = true }
tower = "0.4"
tower-http = { version = "0.4", features = ["trace"] }
tracing = "0.1"
tracing-opentelemetry = "0.18"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "ansi",
  "env-filter",
  "fmt",
  "json",
], optional = true }

[dev-dependencies]
assert2 = "0.3"
hyper = "0.14"
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
opentelemetry-otlp = { version = "0.11", features = [
  "http-proto",
  "reqwest-client",
  "reqwest-rustls",
] }
opentelemetry_api = "0.18"
opentelemetry-proto = { version = "0.2", features = ["gen-tonic", "traces"] }
rstest = "0.17"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17", features = ["full"] }
tonic = "0.8"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }
tokio-stream = { version = "0.1", features = ["net"] }
# need tokio runtime to run smoke tests.
opentelemetry_sdk = { features = [
  "trace",
  "rt-tokio",
  "testing",
], version = "0.18" }
time = { version = "0.3", features = ["macros"] }
hex = "0.4"
# tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[features]
jaeger = ["dep:opentelemetry-jaeger", "tracer"]
otlp = ["dep:opentelemetry-otlp", "tracer"]
tracer = ["dep:opentelemetry-semantic-conventions"]
xray = ["dep:opentelemetry-aws"]
zipkin = ["dep:opentelemetry-zipkin"]
tracing_subscriber_ext = ["dep:tracing-subscriber", "otlp"]

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[package.metadata.release]
pre-release-commit-message = ":rocket: (cargo-release) version {{version}}"
tag-prefix = ""
tag-name = "{{prefix}}{{version}}"
tag-message = ":bookmark: {{version}}"
