[workspace]
resolver = "2"
members = [
  "axum-tracing-opentelemetry",
  "examples/*",
  "fake-opentelemetry-collector",
  "init-tracing-opentelemetry",
  "testing-tracing-opentelemetry",
  "tonic-tracing-opentelemetry",
  "tracing-opentelemetry-instrumentation-sdk",
]

exclude = ["target"]

[workspace.package]
edition = "2021"
version = "0.14.1"
authors = ["David Bernard"]
license = "CC0-1.0"
repository = "https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk"

[workspace.dependencies]
http = "^0.2"
opentelemetry = { version = "0.20", features = [
  "rt-tokio",
  "trace",
], default-features = false }
opentelemetry-otlp = { version = "0.14", default-features = false }
opentelemetry-proto = { version = "0.3", default-features = false }
opentelemetry_api = { version = "0.20", features = [
  "trace",
], default-features = false }
opentelemetry_sdk = { version = "0.20", default-features = false }
tracing = "0.1"
tracing-opentelemetry = "0.21"

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3

[workspace.metadata.workspaces]
no_individual_tags = true
