[package]
name = "tonic-tracing-opentelemetry"
description = "Middlewares and tools to integrate tonic + tracing + opentelemetry."
readme = "README.md"
keywords = ["axum", "tracing", "opentelemetry"]
categories = [
  "development-tools::debugging",
  "development-tools::profiling",
  "web-programming",
]
homepage = "https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/tonic-tracing-opentelemetry"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true


[dependencies]
futures-core = "0.3"
futures-util = { version = "0.3", default_features = false, features = [] }
http = "^0.2"
http-body = "0.4"
hyper = "0.14"
opentelemetry_api = { version = "0.19", features = [
  "trace",
], default-features = false }
pin-project-lite = "0.2"
tonic = { version = "0.9", default-features = false }
tower = { version = "0.4", default-features = false }
tracing = "0.1"
tracing-opentelemetry = "0.19"
tracing-opentelemetry-instrumentation-sdk = { path = "../tracing-opentelemetry-instrumentation-sdk", features = [
  "http",
], version = "0.12" }

[dev-dependencies]
axum = "0.6"
testing-tracing-opentelemetry = { path = "../testing-tracing-opentelemetry" }
fake-opentelemetry-collector = { path = "../fake-opentelemetry-collector" }
assert2 = "0.3"
hyper = "0.14"
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
opentelemetry-otlp = { version = "0.12", features = [
  "http-proto",
  "reqwest-client",
  "reqwest-rustls",
] }
opentelemetry_api = "0.19"
opentelemetry-proto = { version = "0.2", features = ["gen-tonic", "traces"] }
rstest = "0.18"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.27", features = ["full"] }
tower = "0.4"
tracing-subscriber = { version = "0.3", default-features = false, features = [
  "env-filter",
  "fmt",
  "json",
] }
tokio-stream = { version = "0.1", features = ["net"] }
# need tokio runtime to run smoke tests.
opentelemetry_sdk = { features = [
  "trace",
  "rt-tokio",
  "testing",
], version = "0.19" }
