[package]
name = "fake-opentelemetry-collector"
description = "A Fake (basic) opentelemetry collector, useful to test what is collected opentelemetry"
readme = "README.md"
keywords = ["tracing", "opentelemetry", "faker", "mock"]
categories = ["development-tools::testing"]
homepage = "https://github.com/davidB/tracing-opentelemetry-instrumentation-sdk/fake-opentelemetry-collector"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures = "0.3"
hex = "0.4"
opentelemetry = { version = "0.19", features = [
  "rt-tokio",
  "trace",
], default-features = false }
opentelemetry-otlp = { version = "0.12" }
opentelemetry-proto = { version = "0.3", features = ["gen-tonic", "traces"] }
opentelemetry_api = "0.19"
# need tokio runtime to run smoke tests.
opentelemetry_sdk = { features = [
  "trace",
  "rt-tokio",
  "testing",
], version = "0.19" }
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.27", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.8" #should be sync with opentelemetry-proto
tracing = "0.1"

[dev-dependencies]
assert2 = "0.3"
hyper = "0.14"
insta = { version = "1.29.0", features = ["yaml", "redactions"] }
