---
name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: mozilla-actions/sccache-action@v0.0.6
      - run: just check
      - run: just lint
      - run: just test
      - run: just deny
      #- run: just test_each_feature
      - run: ${SCCACHE_PATH} --show-stats
        shell: bash
